author: Sam Doidge
title: 
description: > # this means to ignore newlines until "baseurl:"
  I like to think of ideas and execute them. I continually look to learn and I try not to impose limits on myself.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://samdoidge.com'

# Build settings
markdown: kramdown

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock

# Custom header pages
pages_list:
  About: '/about'
  Archive: '/archive'

sass:
  sass_dir: /assets/sass/
  style: compressed
