author: Sam Doidge
title: 'samdoidge.com'
description: ''
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://samdoidge.com'

# Build settings
markdown: kramdown

permalink: /:title

plugins:
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: /assets/sass/
  style: compressed
