title: Continual improvement
email: sam@samdodige.com
description: > # this means to ignore newlines until "baseurl:"
  I’m a web developer based in the UK, currently contracting for a finance company. I think of ideas and execute them. I continually look to learn and I try not to impose limits on myself.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samdoidge.com"
twitter_username: jekyllrb
github_username: jekyll
disqusid: samdoidge

# Build settings
markdown: kramdown

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock

# Custom header pages
pages_list:
  About: "/about"
  Archive: "/archive"

tags_list:
  Tech: "/tech"
  Other: "/other"

sass:
  sass_dir: /assets/sass/
  style: compressed
